language: erlang
otp_release:
  - 18.0
  - 17.0
  - 17.1
  - 17.4
  - 17.5
  - R16B03
before_install:
  - sudo pip install -q httpbin
  - sudo pip install -q gunicorn
before_script:
  - kerl update releases
  - gunicorn httpbin:app&
